### PR TITLE
Add GroupBy and ToMapF

### PR DESCRIPTION
**Pull request by GiGurra**
useful methods for organizing data. I suspect probably look better in go 1.18 when go gets generics :).

WARNING: I have just started learning Go, so I might be breaking a lot of conventions here. 

This solves https://github.com/thoas/go-funk/issues/56

### CODE REVIEW

**Comment by GiGurra** [comment]
FYI I tested implementing it in go 1.18. So much easier :). No need for reflection in 1.18.

```go
func GroupByT[ElemType interface{}, KeyType comparable](list []ElemType, keyFn func (ElemType) KeyType) map[KeyType][]ElemType {

	count := len(list)

	result := make(map[KeyType][]ElemType, 1 + count/3)

	initGroupCap := 1 + count/3
	if initGroupCap > 10 {
		initGroupCap = 10
	}

	for _, value := range list {
		key := keyFn(value)
		group, exists := result[key]
		if !exists {
			group = make([]ElemType, initGroupCap)
		}
		result[key] = append(group, value)
	}

	return result
}
```

**Comment by GiGurra** [comment]
maybe should just make initial caps 0 for all cases.. idk. you decide

**Comment by samber** [comment]
Please complete the readme ;)

**Comment by ethahae** [comment]
@GiGurra  Hey man, Thanks for your work. I's Great. I already use this GroupBy in my repo. 
The main master branch has not merge it yet is a pity. Maybe you should update the readme and @thoas  will accept it.

**Comment by GiGurra** [comment]
> @GiGurra Hey man, Thanks for your work. I's Great. I already use this GroupBy in my repo. The main master branch has not merge it yet is a pity. Maybe you should update the readme and @thoas will accept it.

Yeah sry, I am unfortunately totally blocked with things I need to take care of personally, so I dont see this being finished soon, unless you want to perhaps make the additions?

**Pull request closed without merging**
